# --- SEGURANÇA (OBRIGATÓRIO) ---
# Remova o # dessas duas linhas abaixo:
jwt.secret=${JWT_SECRET:bWV1U2VncmVkb011aXRvU2VndXJvUGFyYUp3dEFwaTIwMjQ=}
jwt.expiration=3600000

# --- CONFIGURAÇÃO H2 (ATIVO) ---
spring.datasource.url=jdbc:h2:mem:extratodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do H2
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# Configura OpenAI
openai.api-key=${OPENAI_API_KEY:chave-nao-configurada}


# --- CONFIGURAÇÃO POSTGRES (COMENTADO) ---
# spring.datasource.url=jdbc:postgresql://localhost:5432/extrato_popular
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.jpa.hibernate.ddl-auto=update



