spring.datasource.url=jdbc:postgresql://localhost:5432/extrato_popular
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

jwt.secret=bWV1U2VncmVkb011aXRvU2VndXJvUGFyYUp3dEFwaTIwMjQ=
jwt.expiration=3600000
