spring.datasource.url=jdbc:postgresql://localhost:5432/extrato_popular
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

jwt.secret=TROQUE_ANTES_DO_DEPLOY
jwt.expiration=864000000
